Fix some lint errors in unreal GDK docs.
When running:
```
improbadoc lint Documentation \
    --enable_cross_lint=true \
    --doc_type="unreal" \
    --version="alpha"
```

without this change, I got:

```
/home/stefan/Projects/UnrealGDK/SpatialGDK/Documentation/content/cloud-deployment-workflow.md
  L9    linked asset 'https:/docs.google.com/drawings/d/e/2PACX-1vQVcAihbYTNe7TjNsIvkfqIR34Vgw5RESKxboxbvgY5VcgxiI-SZT_M2kuGE8RYMU6sAYWqdkoCjMWt/pub?w=758&h=1162' not found [links-assets]

/home/stefan/Projects/UnrealGDK/SpatialGDK/Documentation/content/local-deployment-workflow.md
  L9    linked asset 'https:/docs.google.com/drawings/d/e/2PACX-1vQCTOucXKMkDJ3-Vpg17_tpUS7IxOXD6Mps-FzWe2tQl3vw5alQPngCnw339cFy3u2NvrcBxhYASKsS/pub?w=710&h=1033' not found [links-assets]

✖ 2 errors in 2 files

        path="/content/spatialos-concepts/workers-and-load-balancing.md" in doctype="unreal",version="latest" referenced from doctype="reference",version="14.0",path="Docs/shared/concepts/workers-load-balancing.md:4" does not exist. [cross-links]
        static asset assets/screen-grabs/toolbar/enable-toolbar.png is not used [unused-assets]
        static asset assets/screen-grabs/toolbar/stop-button-native.png is not used [unused-assets]
        static asset assets/toolbar/deploy-settings.png is not used [unused-assets]
        static asset assets/toolbar/deploy.png is not used [unused-assets]

✖ 5 errors in source directory

ERROR: linting failed (code=Internal, stack={code = Internal desc = linting failed}, code_string=Internal, @tags=[], error=linting failed)
 (@tags=[])
```

With this change, I'm getting only
```
        path="/content/spatialos-concepts/workers-and-load-balancing.md" in doctype="unreal",version="latest" referenced from doctype="reference",version="14.0",path="Docs/shared/concepts/workers-load-balancing.md:4" does not exist. [cross-links]
```

, which is a legit error.